### ISSUE TITLE
火狐兼容问题

### ISSUE THREAD

**Issue by bison1994** [itouzigithub/compatibility-pc#1]
perspective 的值须带单位，虽然规范并不要求一定带单位，但是不带，火狐就不支持
```css
.el {
  perspective: 400px;
}
```

**Comment by bison1994** [comment]
鼠标滚轮事件火狐与其它现代浏览器的差异非常大
- 事件名不一样，其它浏览器为 mousewheel，火狐为 DOMMouseScroll
- 获取滚动量的事件对象属性名不一样，其它浏览器为 event.wheelDelta，火狐为 event.detail
- 滚动方向的正负值不一样，向下滚动时，event.wheelDelta 为负值，event.detail 为正值
- 滚动值的大小也不一样，event.wheelDelta = event.detail * (-40) 

```js
var mousewheelEvt = (/Firefox/i.test(navigator.userAgent))? "DOMMouseScroll" : "mousewheel";
var del = e.wheelDelta || e.detail * -1;
```

[参考](http://www.zhangxinxu.com/wordpress/2013/04/js-mousewheel-dommousescroll-event/)

**Comment by bison1994** [comment]
火狐上 transform 动画会出现抖动，解决方案是加一个轻微的 rotate，hack 味道很浓
```css
.animate {
    -webkit-transform: scale(1.2);
    -moz-transform: scale(1.2) rotate(0.02deg);
}
```
